name: deploy

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Npm
              uses: actions/setup-node@v3
              with:
                  hugo-version: "latest"

            - name: Build Web
              run: npm install
              run: npm publish

            - name: Deploy Web
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: ./public